### ISSUE TITLE
about the loss of nnclr and msf

### ISSUE THREAD

**Issue by aiyeshi** [pc-cp/Mini-SSL#1]
Dear Dr. Chen,
I found that the loss of your NNCLR module is different from that of Lightly.
Similar problem also occurs in MSF and your MNN.
I don't know if this is reasonable. Could you please provide an explanation?

**Comment by pc-cp** [comment]
Hi, aiyeshi, 
just saw your question,
1. Regarding NNCLR's loss, I implemented it by referring to section 3.2 of the original article.
2. MSF is an algorithm that Lightly doesn't seem to have implemented? But anyway its reproduction is very intuitive. 
3. MNN is the algorithm we are proposing.

**Comment by aiyeshi** [comment]
Thank you very much!

**Comment by pc-cp** [comment]
If you have any other questions in future, don't hesitate to ask. : )
